#!/usr/bin/env python3
"""Generates src/midp/font_data.c: 1-bit bitmap fonts (Latin-1) in three
sizes, rendered from DejaVu Sans (Bitstream Vera license) with FreeType
hinting and no antialiasing.

Run inside the build container:
    apt-get install -y python3-pil fonts-dejavu-core
    python3 tools/genfont.py
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
# (point size in pixels, line height) for SIZE_SMALL, SIZE_MEDIUM, SIZE_LARGE
SIZES = [(9, 11), (11, 13), (13, 16)]
FIRST, LAST = 32, 255


def render(px, line_h):
    font = ImageFont.truetype(FONT, px)
    ascent, descent = font.getmetrics()
    top = max(0, (ascent + descent - line_h) // 2)
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        if 0x7f <= code < 0xa0:
            ch = "?"
        adv = max(1, int(round(font.getlength(ch))))
        img = Image.new("1", (adv + 4, line_h), 0)
        draw = ImageDraw.Draw(img)
        draw.fontmode = "1"
        draw.text((0, -top), ch, font=font, fill=1)
        rows = []
        for y in range(line_h):
            bits = 0
            for x in range(adv):
                if img.getpixel((x, y)):
                    bits |= 1 << x
            rows.append(bits)
        glyphs.append((adv, rows))
    baseline = min(line_h, ascent - top)
    return baseline, glyphs


def main():
    out = []
    out.append("/* Generated by tools/genfont.py from DejaVu Sans. Do not edit.")
    out.append(" * DejaVu fonts: Bitstream Vera license, see docs/FONT_LICENSE. */")
    out.append('#include "font_data.h"')
    out.append("")
    defs = []
    for i, (px, line_h) in enumerate(SIZES):
        baseline, glyphs = render(px, line_h)
        bpr = max((g[0] + 7) // 8 for g in glyphs)
        widths = ", ".join(str(g[0]) for g in glyphs)
        out.append(f"static const uint8_t widths{i}[{len(glyphs)}] = {{{widths}}};")
        data = []
        for adv, rows in glyphs:
            for r in rows:
                for b in range(bpr):
                    data.append((r >> (8 * b)) & 0xFF)
        lines = []
        for j in range(0, len(data), 24):
            lines.append("    " + ", ".join(str(v) for v in data[j:j + 24]) + ",")
        out.append(f"static const uint8_t bits{i}[{len(data)}] = {{")
        out.extend(lines)
        out.append("};")
        out.append("")
        defs.append(f"    {{{line_h}, {baseline}, {bpr}, widths{i}, bits{i}}},")
    out.append("const FontData font_data[3] = {")
    out.extend(defs)
    out.append("};")
    with open("src/midp/font_data.c", "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote src/midp/font_data.c", file=sys.stderr)


if __name__ == "__main__":
    main()
