#!/usr/bin/env python3
"""Prints the single-cycle waveforms used by src/audio/synth.c (32 signed
8-bit samples each), built from a few harmonics so they stay smooth when
the hardware resamples them."""
import math

N = 32
WAVES = [
    ("sine", [(1, 1.0)]),
    ("piano", [(1, 1.0), (2, 0.45), (3, 0.25), (4, 0.12)]),
    ("organ", [(1, 1.0), (2, 0.7), (3, 0.5), (4, 0.35), (6, 0.2)]),
    ("saw", [(k, 1.0 / k) for k in range(1, 9)]),
    ("square", [(k, 1.0 / k) for k in range(1, 12, 2)]),
    ("strings", [(k, 1.0 / k ** 1.4) for k in range(1, 8)]),
    ("brass", [(1, 1.0), (2, 0.8), (3, 0.7), (4, 0.5), (5, 0.3), (6, 0.2)]),
    ("triangle", [(k, ((-1) ** ((k - 1) // 2)) / (k * k)) for k in range(1, 10, 2)]),
]

print("/* Generated by tools/genwaves.py. */")
print("static const int8_t waves[%d][%d] __attribute__((aligned(4))) = {" % (len(WAVES), N))
for name, harmonics in WAVES:
    samples = [sum(a * math.sin(2 * math.pi * k * i / N) for k, a in harmonics) for i in range(N)]
    peak = max(abs(s) for s in samples)
    values = [int(round(s / peak * 120)) for s in samples]
    print("    /* %s */ {%s}," % (name, ", ".join(str(v) for v in values)))
print("};")
